[package]
name = "opendr"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "2.0.1"
clap = { version = "4.5.48", features = ["derive"] }
config = "0.15.17"
hex = "0.4.3"
lazy_static = "1.5.0"
ldap-parser = "0.5.0"
ldap3 = { version = "0.12.1" }
log = "0.4.28"
log4rs = "1.4.0"
nom = "8.0.0"
rasn = "0.27.2"
rasn-ldap = "0.27.2"
serde = { version = "1.0.227", features = ["derive"] }
serde_json = "1.0.120"
thiserror = "2.0.16"
tokio = { version = "1.38.0", features = ["full"] }
uuid = { version = "1.9.1", features = ["v4"] }
async-trait = "0.1.80"

[dev-dependencies]
mockall = "0.13.1"
